
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        labelBulan = new javax.swing.JLabel();
        labelTahun = new javax.swing.JLabel();
        labelHasil = new javax.swing.JLabel();
        comboBoxBulan = new javax.swing.JComboBox<>();
        spinnerTahun = new javax.swing.JSpinner();
        buttonHitung = new javax.swing.JButton();
        calendarTanggal = new com.toedter.calendar.JCalendar();
        calenderTanggal2 = new com.toedter.calendar.JCalendar();
        labelSelisih = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBulan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBulan.setText("Bulan");

        labelTahun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTahun.setText("Tahun");

        labelHasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHasil.setText("Hasil");

        comboBoxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"Januari\"", "\"Februari\"", "\"Maret\"", "\"April\"", "\"Mei\"", "\"Juni\"", "\"Juli\"", "\"Agustus\"", "\"September\"", "\"Oktober\"", "\"November\"", "\"Desember\"" }));

        buttonHitung.setText("Hitung");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        labelSelisih.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSelisih.setText("Hasil selisih");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(labelBulan))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(comboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(labelTahun))
                    .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(labelHasil)))
                .addGap(32, 32, 32)
                .addComponent(calendarTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(calenderTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(labelSelisih))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(buttonHitung))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelBulan)
                        .addGap(7, 7, 7)
                        .addComponent(comboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(labelTahun)
                        .addGap(13, 13, 13)
                        .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelHasil))
                    .addComponent(calendarTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calenderTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(labelSelisih)
                .addGap(0, 0, 0)
                .addComponent(buttonHitung)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penghitung Hari dan Selisih Hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        try {
        // Mendapatkan tanggal dari kedua JCalendar
        java.util.Date startDate = calendarTanggal.getDate();
        java.util.Date endDate = calenderTanggal2.getDate();

        // Mengkonversi kedua tanggal ke LocalDate untuk manipulasi lebih mudah
        java.time.LocalDate startLocalDate = startDate.toInstant()
            .atZone(java.time.ZoneId.systemDefault())
            .toLocalDate();

        java.time.LocalDate endLocalDate = endDate.toInstant()
            .atZone(java.time.ZoneId.systemDefault())
            .toLocalDate();
    
        // Menghitung selisih hari
        long daysBetween = java.time.temporal.ChronoUnit.DAYS.between(startLocalDate, endLocalDate);
        
        // Menampilkan hasil selisih hari pada labelSelisih
        labelSelisih.setText("Selisih Hari: " + daysBetween + " hari");

        // Mendapatkan tanggal dari JCalendar untuk menghitung jumlah hari dalam bulan
        java.util.Date selectedDate = calendarTanggal.getDate();

        // Konversi ke LocalDate (untuk memudahkan manipulasi tanggal)
        java.time.LocalDate localDate = selectedDate.toInstant()
            .atZone(java.time.ZoneId.systemDefault())
            .toLocalDate();

        // Mendapatkan bulan dan tahun dari tanggal
        int tahunDipilih = localDate.getYear();
        int bulanDipilih = localDate.getMonthValue();

        // Menghitung jumlah hari dalam bulan
        java.time.YearMonth yearMonth = java.time.YearMonth.of(tahunDipilih, bulanDipilih);
        int jumlahHari = yearMonth.lengthOfMonth();

        // Menampilkan hasil jumlah hari dalam bulan pada labelHasil
        labelHasil.setText("Jumlah Hari: " + jumlahHari);

        // Mengupdate comboBoxBulan dan spinnerTahun jika diperlukan
        comboBoxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Januari", "Februari", "Maret", "April", "Mei", "Juni",
            "Juli", "Agustus", "September", "Oktober", "November", "Desember"
        }));

        spinnerTahun.setModel(new javax.swing.SpinnerNumberModel(
            java.time.Year.now().getValue(), // Tahun saat ini
            1900, // Tahun minimal
            2100, // Tahun maksimal
            1     // Increment
        ));

    } catch (Exception e) {
        // Menangani jika ada error
        labelSelisih.setText("Error: Pastikan tanggal sudah dipilih dengan benar!");
    }
    }//GEN-LAST:event_buttonHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHitung;
    private com.toedter.calendar.JCalendar calendarTanggal;
    private com.toedter.calendar.JCalendar calenderTanggal2;
    private javax.swing.JComboBox<String> comboBoxBulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelSelisih;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
